=== endeavourhealth/EmisWebPoller/Endeavour.EmisWebPollerService/Configuration/Configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Endeavour.EmisWebPollerService">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Configuration" type="Configuration"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Configuration">
		<xs:sequence>
			<xs:element name="EndeavourServiceEndpoint" type="NonEmptyString"/>
			<xs:element name="KeycloakBaseUrl" type="NonEmptyString"/>
			<xs:element name="KeycloakRealm" type="NonEmptyString"/>
			<xs:element name="KeycloakClientId" type="NonEmptyString"/>
			<xs:element name="KeycloakUserName" type="NonEmptyString"/>
			<xs:element name="KeycloakPassword" type="NonEmptyString"/>
			<xs:element name="IsKeycloakPasswordEncrypted" type="xs:boolean"/>
			<xs:element name="OdsCode" type="NonEmptyString"/>
			<xs:element name="ServiceThreadSleepMilliseconds" type="xs:int"/>
			<xs:element name="EmisWebCdb" type="xs:int"/>
			<xs:element name="EmisWebIPAddress" type="NonEmptyString"/>
			<xs:element name="PartnerApiKey" type="NonEmptyString"/>
			<xs:element name="PartnerApiUserName" type="NonEmptyString"/>
			<xs:element name="PartnerApiPassword" type="NonEmptyString"/>
			<xs:element name="IsPartnerApiPasswordEncrypted" type="xs:boolean"/>
			<xs:element name="SynchronizationFrequencyMinutes" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="NonEmptyString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:pattern value=".*[^\s].*"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== endeavourhealth/EmisWebPoller/Endeavour.EmisWebPollerService/Configuration/Configuration.xml
<?xml version="1.0" encoding="utf-8"?>
<Endeavour.EmisWebPollerService xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="Configuration.xsd">
  <Configuration>
    
    <!-- Endeavour endpoint for receiving patient records -->
    <EndeavourServiceEndpoint>https://deveds.endeavourhealth.net/eds-api/api/PostMessageAsync</EndeavourServiceEndpoint>

    <!-- Endeavour Keycloak endpoint -->
    <KeycloakBaseUrl>https://devauth.endeavourhealth.net/auth</KeycloakBaseUrl>

    <!-- Endeavour Keycloak Realm -->
    <KeycloakRealm>endeavour</KeycloakRealm>

    <!-- Endeavour Keycloak ClientId -->
    <KeycloakClientId>eds-ui</KeycloakClientId>

    <!-- Endeavour Keycloak UserName -->
    <KeycloakUserName>professional</KeycloakUserName>

    <!-- Endeavour Keycloak Password -->
    <KeycloakPassword>password</KeycloakPassword>

    <!-- Whether the KeycloakPassword is encrypted or not -->
    <!-- If the password is not encrypted, set the value to false, and the poller will encrypt it on first run -->
    <IsKeycloakPasswordEncrypted>false</IsKeycloakPasswordEncrypted>

    <!-- ODS code for the organisation this is running at -->
    <!-- Note: used as the source.name in the MessageHeader resouse sent in the Bundle to the Endeavour Service Api -->
    <OdsCode>Y00001</OdsCode>

    <!-- Number of milliseconds for Windows service thread to sleep for after completing one cycle -->
    <!-- Note: setting this too high will lead in the service becoming unresponsive -->
    <ServiceThreadSleepMilliseconds>1000</ServiceThreadSleepMilliseconds>
    
    <!-- EMIS Web CDB number for the site this is running at -->
    <EmisWebCdb>50002</EmisWebCdb>
    
    <!-- IP address of EMIS' EMAS server.  This is provided by EMIS -->
    <EmisWebIPAddress>185.13.72.90</EmisWebIPAddress>
    
    <!-- Endeavour Health Partner API key.  Also provided by EMIS. -->
    <PartnerApiKey>417fd2ff-aeba-46e7-82b6-9ceb496dcfdf</PartnerApiKey>
    
    <!-- Partner API username.  This is specific to the site being installed at. -->
    <PartnerApiUserName>emistest</PartnerApiUserName>
    
    <!-- Encrypted partner API password.  This is specific to the site being installed at. -->
    <!-- Note: this may be different from the same as the client login password -->
    <PartnerApiPassword>Emis1234</PartnerApiPassword>
    
    <!-- Whether the PartnerApiPassword is encrypted or not -->
    <!-- If the password is not encrypted, set the value to false, and the poller will encrypt it on first run -->
    <IsPartnerApiPasswordEncrypted>false</IsPartnerApiPasswordEncrypted>

    <!-- Number of minutes to wait between each synchronization check -->
    <SynchronizationFrequencyMinutes>15</SynchronizationFrequencyMinutes>
    
  </Configuration>
</Endeavour.EmisWebPollerService>
